// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMYuE_dLTyaxrgq5D9QBHIK5yPRfNehU',
    appId: '1:631203151510:web:e848ab5a5887090da44cb7',
    messagingSenderId: '631203151510',
    projectId: 'biblioteca-a7e8a',
    authDomain: 'biblioteca-a7e8a.firebaseapp.com',
    storageBucket: 'biblioteca-a7e8a.firebasestorage.app',
    measurementId: 'G-LG2WTMVT7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOIzeK7shF-Sxtr6tDDx2exXiBl7WCmgg',
    appId: '1:631203151510:android:475ef38505fd7649a44cb7',
    messagingSenderId: '631203151510',
    projectId: 'biblioteca-a7e8a',
    storageBucket: 'biblioteca-a7e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe_8RYjK1NhdsZaCCtW71W0hE2Eg68Hgo',
    appId: '1:631203151510:ios:1d75933547fd9c72a44cb7',
    messagingSenderId: '631203151510',
    projectId: 'biblioteca-a7e8a',
    storageBucket: 'biblioteca-a7e8a.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe_8RYjK1NhdsZaCCtW71W0hE2Eg68Hgo',
    appId: '1:631203151510:ios:1d75933547fd9c72a44cb7',
    messagingSenderId: '631203151510',
    projectId: 'biblioteca-a7e8a',
    storageBucket: 'biblioteca-a7e8a.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMYuE_dLTyaxrgq5D9QBHIK5yPRfNehU',
    appId: '1:631203151510:web:ba968c3e21259f4aa44cb7',
    messagingSenderId: '631203151510',
    projectId: 'biblioteca-a7e8a',
    authDomain: 'biblioteca-a7e8a.firebaseapp.com',
    storageBucket: 'biblioteca-a7e8a.firebasestorage.app',
    measurementId: 'G-DCJW44N1QR',
  );
}
